### ISSUE TITLE
change location of projects section

### ISSUE THREAD

**Issue by timpauli** [victoriadotdev/hugo-theme-introduction#133]
Hi!
 
First of all thank you for creating this great theme.
Is it possible to change the order of the sections so that the projects section comes right after the about section?
Cant figure out how to do that.
Thank you very much in advance.

**Comment by hanzei** [comment]
This is not possible with a setting. But you can provide a modified copy of https://github.com/vickylai/hugo-theme-introduction/blob/master/layouts/index.html in your `layouts` directory.

**Comment by inkeye** [comment]
So basically you would need to add the __index.md_ of _projects_ and and _blog_ to the sorted loop of [line 43](https://github.com/vickylai/hugo-theme-introduction/blob/a8f42fd1d688424555b012fa55820ea9f982e3a5/layouts/index.html#L43)
but then treat them special inside the loop.
So you could specify the placement of them with the _weight_ attribute.
Unfortunately I dont have the time currently to look into this since I am not familiar with hugo go templating.
In my opinion it would also be cleaner solution in general: to let the user decide where to put each section of the website.
thx anyways for pointing me there

**Comment by hanzei** [comment]
> In my opinion it would also be cleaner solution in general: to let the user decide where to put each section of the website.

That is not no easy. How would you design the setting to do this?

**Comment by timpauli** [comment]
Just the same like in the home section with the `weight` property.

But mabye you got my use of the word 

> user

wrong here. With user I dont mean the visitor of the website, I mean the builder of the website with the template.

**Comment by hanzei** [comment]
> Just the same like in the home section with the `weight` property.

Where would you define this `weight`? Would you be open to share an example of a configuration file?

**Comment by timpauli** [comment]
In `content/en/home/foo.md` for example you specify the position like this:

```
---
title: "foo"
weight: 1
---
bar
```

I would just apply the same concept to `content/en/projects/_index.md`.

**Comment by hanzei** [comment]
Seams reasonable. Would you be open to implement this?
