### ISSUE TITLE
It seems blog doesn't work

### ISSUE THREAD

**Issue by graphenn** [victoriadotdev/hugo-theme-introduction#151]
After update to new version 76123d6, It seems "blog" section doesn't work.
It seems to be handled as a normal Lorem Ipsum.

```
Blog
Here is some introduction text for my blog. You can set this text in the /blog/_index.md file. This page uses the /layouts/blog/list.html template.
```

**Comment by k-j-kleist** [comment]
Are you using Windows, by any chance? I do, and I had the same issue.

An hour's debugging revealed that a known Hugo feature is to blame: https://github.com/gohugoio/hugo/issues/3187

As a workaround, I modified `layouts/index.htm`, and inserted
`{{ $fileDir := replace .File.Dir "\\" "/" }}` before the two tests here:

https://github.com/victoriadotdev/hugo-theme-introduction/blob/master/layouts/index.html#L58-L64

In the tests I then used `$fileDir` instead of `.File.Dir`, which solved the problem.

Maybe I'm naïve, because I've been using Hugo just several days. Or simply because I'm an old fart. But isn't it a shame that this has not been fixed in Hugo? Why is the directory separator included at all in `.File.Dir` et al.?

**Comment by YShane** [comment]
This is still a pretty big issue.  Could this possibly be dealt with? Would open a pull request but I imagine it can't be more than a few lines to change.

**Comment by YShane** [comment]
It did now, actually. Cheers!

**Comment by hanzei** [comment]
I will look into this

**Comment by graphenn** [comment]
It works now! Thanks
